-- Missing indexes for frequently queried columns

-- Payment table
CREATE INDEX IF NOT EXISTS IDX_PAYMENT_USER_ID ON PAYMENT(USER_ID);
CREATE INDEX IF NOT EXISTS IDX_PAYMENT_PARTY_ID ON PAYMENT(PARTY_ID);
CREATE INDEX IF NOT EXISTS IDX_PAYMENT_STATUS_DATE ON PAYMENT(PAYMENT_STATUS, PAYMENT_DATE, PARTY_ID);

-- Deposit table
CREATE INDEX IF NOT EXISTS IDX_DEPOSIT_USER_ID ON DEPOSIT(USER_ID);
CREATE INDEX IF NOT EXISTS IDX_DEPOSIT_PARTY_USER ON DEPOSIT(PARTY_ID, USER_ID);

-- Party table
CREATE INDEX IF NOT EXISTS IDX_PARTY_STATUS_START ON PARTY(PARTY_STATUS, START_DATE);
CREATE INDEX IF NOT EXISTS IDX_PARTY_LEADER ON PARTY(PARTY_LEADER_ID);

-- Party Member table
CREATE INDEX IF NOT EXISTS IDX_PARTY_MEMBER_USER ON PARTY_MEMBER(USER_ID);

-- Settlement table
CREATE INDEX IF NOT EXISTS IDX_SETTLEMENT_LEADER ON SETTLEMENT(PARTY_LEADER_ID);
CREATE INDEX IF NOT EXISTS IDX_SETTLEMENT_STATUS ON SETTLEMENT(SETTLEMENT_STATUS);
