-- AI 월간 리포트 저장 테이블
CREATE TABLE IF NOT EXISTS AI_MONTHLY_REPORT (
    REPORT_ID     INT           NOT NULL AUTO_INCREMENT,
    USER_ID       VARCHAR(36)   NOT NULL,
    TARGET_MONTH  VARCHAR(7)    NOT NULL,   -- 'yyyy-MM'
    SUMMARY       TEXT          NOT NULL,   -- AI 생성 요약
    TOTAL_PAID    INT           NOT NULL DEFAULT 0,
    PAYMENT_COUNT INT           NOT NULL DEFAULT 0,
    CREATED_AT    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (REPORT_ID),
    UNIQUE KEY UK_USER_MONTH (USER_ID, TARGET_MONTH)
);
