-- AI 비정상 결제 감지 알림 저장 테이블
CREATE TABLE IF NOT EXISTS AI_FRAUD_ALERT (
    ALERT_ID     INT          NOT NULL AUTO_INCREMENT,
    PAYMENT_ID   INT          NULL,
    USER_ID      VARCHAR(36)  NOT NULL,
    PARTY_ID     INT          NULL,
    AMOUNT       INT          NOT NULL,
    TARGET_MONTH VARCHAR(7)   NOT NULL,
    RISK_LEVEL   VARCHAR(10)  NOT NULL,   -- LOW | MEDIUM | HIGH
    REASONS      TEXT         NOT NULL,   -- JSON 배열 문자열
    AI_ANALYSIS  TEXT         NOT NULL,   -- LLM 원본 응답
    CREATED_AT   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ALERT_ID),
    INDEX IDX_USER_ID (USER_ID),
    INDEX IDX_CREATED_AT (CREATED_AT)
);
