-- Add status and memo columns to AI_FRAUD_ALERT table
ALTER TABLE AI_FRAUD_ALERT ADD COLUMN IF NOT EXISTS STATUS VARCHAR(20) DEFAULT 'PENDING';
ALTER TABLE AI_FRAUD_ALERT ADD COLUMN IF NOT EXISTS MEMO TEXT;
ALTER TABLE AI_FRAUD_ALERT ADD COLUMN IF NOT EXISTS UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
